sudo: required
services:
    - docker
before_install:
    - docker build -t react-app -f ./react-app/Dockerfile.dev react-app/
script:
    - docker run -e CI=true -v /app/node_modules -v $(pwd)/react-app:/app react-app npm run test
after_success:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_ACCESS_TOKEN"
    - docker-compose -f compose.travis.yml build
    - docker-compose -f compose.travis.yml push
deploy:
    on:
        branch: master
    provider: elasticbeanstalk
    region: us-east-1
    app: "Docker Fibonacci"
    env: "DockerFibonacci-env2"
    bucket_name: "elasticbeanstalk-us-east-1-297436977708"
    bucket_path: "docker-fibonacci"
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
