sudo: required
services:
    - docker
before_install:
    - docker build -t react-app -f ./react-app/Dockerfile.dev react-app/
script:
    - docker run -e CI=true -v /app/node_modules -v $(pwd)/react-app:/app react-app npm run test
after_success:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_ACCESS_TOKEN"
    - docker-compose build
    - docker-compose push
