sudo: required
services:
    - docker
before_install:
    - docker build -t react-app -f ./react-app/Dockerfile.dev react-app/
script:
    - docker run -e CI=true -v /app/node_modules -v ./react-app:/app react-app npm run test
