services:
  nginx:
    image: letsgoforitanik/fibonacci-nginx
    restart: always
    depends_on:
      - react
    ports:
      - 80:80

  api:
    image: letsgoforitanik/fibonacci-api
    restart: always

    
  react:
    image: letsgoforitanik/fibonacci-react
    restart: always
    depends_on:
      - api

  worker:
    image: letsgoforitanik/fibonacci-worker
    restart: always



volumes:
  postgresdata: {}